version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 700
    type:
      - file
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 700
    type:
      - directory

hooks:
  ApplicationStop:
    - location: codedeploy/applicationStop.sh
      timeout: 300

  AfterInstall:
    - location: codedeploy/afterInstall.sh
      timeout: 300

  ApplicationStart:
    - location: codedeploy/applicationStart.sh
      timeout: 300