version: 2
pr-check-workflow:

  jobs:
    -pr_check
  
    build:
      docker:
        # specify the version you desire here
        - image: circleci/node:8.10.0

     

      working_directory: ~/repo

      steps:
        - checkout
        - run: npm install

        - run: npm test