version: 2
jobs:
  pr-check:

    working_directory: ~/webapp

    docker:
      - image: circleci/node:8.10.0
      - image: circleci/mysql:8.0.4
        environment:
        MYSQL_DATABASE: UserDetails
        MYSQL_USER: sharwari
        MYSQL_PASSWORD: password


    steps:
      - checkout

      - run: npm install
      - run: npm test


build:
  working_directory: ~/webapp

  docker:
    - image: circleci/node:8.10.0
    - image: circleci/mysql:8.0.4
      environment:
        MYSQL_DATABASE: UserDetails
        MYSQL_USER: sharwari
        MYSQL_PASSWORD: password

  steps:
    - checkout
    
    - run: npm install

    - run: npm test

workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build-deploy-workflow:
    jobs:
    - build